//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int RoomNum { get; set; }
        public Nullable<int> RoomType { get; set; }
        public string RoomState { get; set; }
        public Nullable<int> BedNum { get; set; }
        public Nullable<int> GustNum { get; set; }
        public string Description { get; set; }
    
        public virtual RoomType RoomType1 { get; set; }
    }
}
