//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomType
    {
        public RoomType()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AddBed { get; set; }
        public Nullable<decimal> BedPrice { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
    }
}
