//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.LockOwnersTable {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblSurrogateLockOwnerId;
	protected global::System.Web.UI.WebControls.Label lblLockExpiration;
	protected global::System.Web.UI.WebControls.Label lblWorkflowHostType;
	protected global::System.Web.UI.WebControls.Label lblMachineName;
	protected global::System.Web.UI.WebControls.CheckBox chkEnqueueCommand;
	protected global::System.Web.UI.WebControls.CheckBox chkDeletesInstanceOnCompletion;
	protected global::System.Web.UI.WebControls.Label lblPrimitiveLockOwnerData;
	protected global::System.Web.UI.WebControls.Label lblComplexLockOwnerData;
	protected global::System.Web.UI.WebControls.Label lblWriteOnlyPrimitiveLockOwnerData;
	protected global::System.Web.UI.WebControls.Label lblWriteOnlyComplexLockOwnerData;
	protected global::System.Web.UI.WebControls.Label lblEncodingOption;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
