//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.WF_Step {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtsubTime;
		protected global::System.Web.UI.WebControls.TextBox txtProcessTime;
		protected global::System.Web.UI.WebControls.TextBox txtProcessBy;
		protected global::System.Web.UI.WebControls.TextBox txtStepName;
		protected global::System.Web.UI.WebControls.TextBox txtComment;
		protected global::System.Web.UI.WebControls.TextBox txtFlowTo;
		protected global::System.Web.UI.WebControls.CheckBox chkIsStart;
		protected global::System.Web.UI.WebControls.CheckBox chkIsEnd;
		protected global::System.Web.UI.WebControls.TextBox txtState;
		protected global::System.Web.UI.WebControls.TextBox txtParentStepId;
		protected global::System.Web.UI.WebControls.TextBox txtSort;
		protected global::System.Web.UI.WebControls.TextBox txtWF_InstanceID;
		protected global::System.Web.UI.WebControls.TextBox txtInstanceId;
		protected global::System.Web.UI.WebControls.CheckBox chkIsProcessed;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
