//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.WF_Step {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblsubTime;
	protected global::System.Web.UI.WebControls.Label lblProcessTime;
	protected global::System.Web.UI.WebControls.Label lblProcessBy;
	protected global::System.Web.UI.WebControls.Label lblStepName;
	protected global::System.Web.UI.WebControls.Label lblComment;
	protected global::System.Web.UI.WebControls.Label lblFlowTo;
	protected global::System.Web.UI.WebControls.CheckBox chkIsStart;
	protected global::System.Web.UI.WebControls.CheckBox chkIsEnd;
	protected global::System.Web.UI.WebControls.Label lblState;
	protected global::System.Web.UI.WebControls.Label lblParentStepId;
	protected global::System.Web.UI.WebControls.Label lblSort;
	protected global::System.Web.UI.WebControls.Label lblWF_InstanceID;
	protected global::System.Web.UI.WebControls.Label lblInstanceId;
	protected global::System.Web.UI.WebControls.CheckBox chkIsProcessed;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
