//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.WF_Instance {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblSubBy;
	protected global::System.Web.UI.WebControls.Label lblSubTime;
	protected global::System.Web.UI.WebControls.Label lblOutTime;
	protected global::System.Web.UI.WebControls.Label lblstate;
	protected global::System.Web.UI.WebControls.Label lblResult;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblLevel;
	protected global::System.Web.UI.WebControls.Label lblWF_TempID;
	protected global::System.Web.UI.WebControls.Label lblInstanceId;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
