//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.InstancePromotedPropertiesTable {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtSurrogateInstanceId;
		protected global::System.Web.UI.WebControls.TextBox txtPromotionName;
		protected global::System.Web.UI.WebControls.TextBox txtValue1;
		protected global::System.Web.UI.WebControls.TextBox txtValue2;
		protected global::System.Web.UI.WebControls.TextBox txtValue3;
		protected global::System.Web.UI.WebControls.TextBox txtValue4;
		protected global::System.Web.UI.WebControls.TextBox txtValue5;
		protected global::System.Web.UI.WebControls.TextBox txtValue6;
		protected global::System.Web.UI.WebControls.TextBox txtValue7;
		protected global::System.Web.UI.WebControls.TextBox txtValue8;
		protected global::System.Web.UI.WebControls.TextBox txtValue9;
		protected global::System.Web.UI.WebControls.TextBox txtValue10;
		protected global::System.Web.UI.WebControls.TextBox txtValue11;
		protected global::System.Web.UI.WebControls.TextBox txtValue12;
		protected global::System.Web.UI.WebControls.TextBox txtValue13;
		protected global::System.Web.UI.WebControls.TextBox txtValue14;
		protected global::System.Web.UI.WebControls.TextBox txtValue15;
		protected global::System.Web.UI.WebControls.TextBox txtValue16;
		protected global::System.Web.UI.WebControls.TextBox txtValue17;
		protected global::System.Web.UI.WebControls.TextBox txtValue18;
		protected global::System.Web.UI.WebControls.TextBox txtValue19;
		protected global::System.Web.UI.WebControls.TextBox txtValue20;
		protected global::System.Web.UI.WebControls.TextBox txtValue21;
		protected global::System.Web.UI.WebControls.TextBox txtValue22;
		protected global::System.Web.UI.WebControls.TextBox txtValue23;
		protected global::System.Web.UI.WebControls.TextBox txtValue24;
		protected global::System.Web.UI.WebControls.TextBox txtValue25;
		protected global::System.Web.UI.WebControls.TextBox txtValue26;
		protected global::System.Web.UI.WebControls.TextBox txtValue27;
		protected global::System.Web.UI.WebControls.TextBox txtValue28;
		protected global::System.Web.UI.WebControls.TextBox txtValue29;
		protected global::System.Web.UI.WebControls.TextBox txtValue30;
		protected global::System.Web.UI.WebControls.TextBox txtValue31;
		protected global::System.Web.UI.WebControls.TextBox txtValue32;
		protected global::System.Web.UI.WebControls.TextBox txtValue33;
		protected global::System.Web.UI.WebControls.TextBox txtValue34;
		protected global::System.Web.UI.WebControls.TextBox txtValue35;
		protected global::System.Web.UI.WebControls.TextBox txtValue36;
		protected global::System.Web.UI.WebControls.TextBox txtValue37;
		protected global::System.Web.UI.WebControls.TextBox txtValue38;
		protected global::System.Web.UI.WebControls.TextBox txtValue39;
		protected global::System.Web.UI.WebControls.TextBox txtValue40;
		protected global::System.Web.UI.WebControls.TextBox txtValue41;
		protected global::System.Web.UI.WebControls.TextBox txtValue42;
		protected global::System.Web.UI.WebControls.TextBox txtValue43;
		protected global::System.Web.UI.WebControls.TextBox txtValue44;
		protected global::System.Web.UI.WebControls.TextBox txtValue45;
		protected global::System.Web.UI.WebControls.TextBox txtValue46;
		protected global::System.Web.UI.WebControls.TextBox txtValue47;
		protected global::System.Web.UI.WebControls.TextBox txtValue48;
		protected global::System.Web.UI.WebControls.TextBox txtValue49;
		protected global::System.Web.UI.WebControls.TextBox txtValue50;
		protected global::System.Web.UI.WebControls.TextBox txtValue51;
		protected global::System.Web.UI.WebControls.TextBox txtValue52;
		protected global::System.Web.UI.WebControls.TextBox txtValue53;
		protected global::System.Web.UI.WebControls.TextBox txtValue54;
		protected global::System.Web.UI.WebControls.TextBox txtValue55;
		protected global::System.Web.UI.WebControls.TextBox txtValue56;
		protected global::System.Web.UI.WebControls.TextBox txtValue57;
		protected global::System.Web.UI.WebControls.TextBox txtValue58;
		protected global::System.Web.UI.WebControls.TextBox txtValue59;
		protected global::System.Web.UI.WebControls.TextBox txtValue60;
		protected global::System.Web.UI.WebControls.TextBox txtValue61;
		protected global::System.Web.UI.WebControls.TextBox txtValue62;
		protected global::System.Web.UI.WebControls.TextBox txtValue63;
		protected global::System.Web.UI.WebControls.TextBox txtValue64;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
