//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.InstancePromotedPropertiesTable {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblSurrogateInstanceId;
	protected global::System.Web.UI.WebControls.Label lblPromotionName;
	protected global::System.Web.UI.WebControls.Label lblValue1;
	protected global::System.Web.UI.WebControls.Label lblValue2;
	protected global::System.Web.UI.WebControls.Label lblValue3;
	protected global::System.Web.UI.WebControls.Label lblValue4;
	protected global::System.Web.UI.WebControls.Label lblValue5;
	protected global::System.Web.UI.WebControls.Label lblValue6;
	protected global::System.Web.UI.WebControls.Label lblValue7;
	protected global::System.Web.UI.WebControls.Label lblValue8;
	protected global::System.Web.UI.WebControls.Label lblValue9;
	protected global::System.Web.UI.WebControls.Label lblValue10;
	protected global::System.Web.UI.WebControls.Label lblValue11;
	protected global::System.Web.UI.WebControls.Label lblValue12;
	protected global::System.Web.UI.WebControls.Label lblValue13;
	protected global::System.Web.UI.WebControls.Label lblValue14;
	protected global::System.Web.UI.WebControls.Label lblValue15;
	protected global::System.Web.UI.WebControls.Label lblValue16;
	protected global::System.Web.UI.WebControls.Label lblValue17;
	protected global::System.Web.UI.WebControls.Label lblValue18;
	protected global::System.Web.UI.WebControls.Label lblValue19;
	protected global::System.Web.UI.WebControls.Label lblValue20;
	protected global::System.Web.UI.WebControls.Label lblValue21;
	protected global::System.Web.UI.WebControls.Label lblValue22;
	protected global::System.Web.UI.WebControls.Label lblValue23;
	protected global::System.Web.UI.WebControls.Label lblValue24;
	protected global::System.Web.UI.WebControls.Label lblValue25;
	protected global::System.Web.UI.WebControls.Label lblValue26;
	protected global::System.Web.UI.WebControls.Label lblValue27;
	protected global::System.Web.UI.WebControls.Label lblValue28;
	protected global::System.Web.UI.WebControls.Label lblValue29;
	protected global::System.Web.UI.WebControls.Label lblValue30;
	protected global::System.Web.UI.WebControls.Label lblValue31;
	protected global::System.Web.UI.WebControls.Label lblValue32;
	protected global::System.Web.UI.WebControls.Label lblValue33;
	protected global::System.Web.UI.WebControls.Label lblValue34;
	protected global::System.Web.UI.WebControls.Label lblValue35;
	protected global::System.Web.UI.WebControls.Label lblValue36;
	protected global::System.Web.UI.WebControls.Label lblValue37;
	protected global::System.Web.UI.WebControls.Label lblValue38;
	protected global::System.Web.UI.WebControls.Label lblValue39;
	protected global::System.Web.UI.WebControls.Label lblValue40;
	protected global::System.Web.UI.WebControls.Label lblValue41;
	protected global::System.Web.UI.WebControls.Label lblValue42;
	protected global::System.Web.UI.WebControls.Label lblValue43;
	protected global::System.Web.UI.WebControls.Label lblValue44;
	protected global::System.Web.UI.WebControls.Label lblValue45;
	protected global::System.Web.UI.WebControls.Label lblValue46;
	protected global::System.Web.UI.WebControls.Label lblValue47;
	protected global::System.Web.UI.WebControls.Label lblValue48;
	protected global::System.Web.UI.WebControls.Label lblValue49;
	protected global::System.Web.UI.WebControls.Label lblValue50;
	protected global::System.Web.UI.WebControls.Label lblValue51;
	protected global::System.Web.UI.WebControls.Label lblValue52;
	protected global::System.Web.UI.WebControls.Label lblValue53;
	protected global::System.Web.UI.WebControls.Label lblValue54;
	protected global::System.Web.UI.WebControls.Label lblValue55;
	protected global::System.Web.UI.WebControls.Label lblValue56;
	protected global::System.Web.UI.WebControls.Label lblValue57;
	protected global::System.Web.UI.WebControls.Label lblValue58;
	protected global::System.Web.UI.WebControls.Label lblValue59;
	protected global::System.Web.UI.WebControls.Label lblValue60;
	protected global::System.Web.UI.WebControls.Label lblValue61;
	protected global::System.Web.UI.WebControls.Label lblValue62;
	protected global::System.Web.UI.WebControls.Label lblValue63;
	protected global::System.Web.UI.WebControls.Label lblValue64;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
