//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.InstancesTable {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        		protected global::System.Web.UI.WebControls.TextBox txtId;
	protected global::System.Web.UI.WebControls.Label lblSurrogateInstanceId;
		protected global::System.Web.UI.WebControls.TextBox txtSurrogateLockOwnerId;
		protected global::System.Web.UI.WebControls.TextBox txtPrimitiveDataProperties;
		protected global::System.Web.UI.WebControls.TextBox txtComplexDataProperties;
		protected global::System.Web.UI.WebControls.TextBox txtWriteOnlyPrimitiveDataProperties;
		protected global::System.Web.UI.WebControls.TextBox txtWriteOnlyComplexDataProperties;
		protected global::System.Web.UI.WebControls.TextBox txtMetadataProperties;
		protected global::System.Web.UI.WebControls.TextBox txtDataEncodingOption;
		protected global::System.Web.UI.WebControls.TextBox txtMetadataEncodingOption;
		protected global::System.Web.UI.WebControls.TextBox txtVersion;
		protected global::System.Web.UI.WebControls.TextBox txtPendingTimer;
		protected global::System.Web.UI.WebControls.TextBox txtCreationTime;
		protected global::System.Web.UI.WebControls.TextBox txtLastUpdated;
		protected global::System.Web.UI.WebControls.TextBox txtWorkflowHostType;
		protected global::System.Web.UI.WebControls.TextBox txtServiceDeploymentId;
		protected global::System.Web.UI.WebControls.TextBox txtSuspensionExceptionName;
		protected global::System.Web.UI.WebControls.TextBox txtSuspensionReason;
		protected global::System.Web.UI.WebControls.TextBox txtBlockingBookmarks;
		protected global::System.Web.UI.WebControls.TextBox txtLastMachineRunOn;
		protected global::System.Web.UI.WebControls.TextBox txtExecutionStatus;
		protected global::System.Web.UI.WebControls.CheckBox chkIsInitialized;
		protected global::System.Web.UI.WebControls.CheckBox chkIsSuspended;
		protected global::System.Web.UI.WebControls.CheckBox chkIsReadyToRun;
		protected global::System.Web.UI.WebControls.CheckBox chkIsCompleted;
	protected global::System.Web.UI.WebControls.Button btnAdd;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
