//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.42
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Web.InstancesTable {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblSurrogateInstanceId;
	protected global::System.Web.UI.WebControls.Label lblSurrogateLockOwnerId;
	protected global::System.Web.UI.WebControls.Label lblPrimitiveDataProperties;
	protected global::System.Web.UI.WebControls.Label lblComplexDataProperties;
	protected global::System.Web.UI.WebControls.Label lblWriteOnlyPrimitiveDataProperties;
	protected global::System.Web.UI.WebControls.Label lblWriteOnlyComplexDataProperties;
	protected global::System.Web.UI.WebControls.Label lblMetadataProperties;
	protected global::System.Web.UI.WebControls.Label lblDataEncodingOption;
	protected global::System.Web.UI.WebControls.Label lblMetadataEncodingOption;
	protected global::System.Web.UI.WebControls.Label lblVersion;
	protected global::System.Web.UI.WebControls.Label lblPendingTimer;
	protected global::System.Web.UI.WebControls.Label lblCreationTime;
	protected global::System.Web.UI.WebControls.Label lblLastUpdated;
	protected global::System.Web.UI.WebControls.Label lblWorkflowHostType;
	protected global::System.Web.UI.WebControls.Label lblServiceDeploymentId;
	protected global::System.Web.UI.WebControls.Label lblSuspensionExceptionName;
	protected global::System.Web.UI.WebControls.Label lblSuspensionReason;
	protected global::System.Web.UI.WebControls.Label lblBlockingBookmarks;
	protected global::System.Web.UI.WebControls.Label lblLastMachineRunOn;
	protected global::System.Web.UI.WebControls.Label lblExecutionStatus;
	protected global::System.Web.UI.WebControls.CheckBox chkIsInitialized;
	protected global::System.Web.UI.WebControls.CheckBox chkIsSuspended;
	protected global::System.Web.UI.WebControls.CheckBox chkIsReadyToRun;
	protected global::System.Web.UI.WebControls.CheckBox chkIsCompleted;


        /// <summary>
        /// Master 属性。
        /// </summary>
        /// <remarks>
        /// 自动生成的属性。
        /// </remarks>
        public new BookShop.Web.MasterPage Master {
            get {
                return ((BookShop.Web.MasterPage)(base.Master));
            }
        }
    }
}
